#!/bin/bash


blue='\e[1;36m'
endcol='\e[0m'

music="$HOME"/music
photos="$HOME"/phone/photos
shared_dir="$HOME"/phone/shared

phone_music="/storage/extSdCard"
phone_photos="/storage/extSdCard/DCIM/Camera/"
phone_shared_directory="/sdcard/Download"

menu() {
  adb devices

  echo "Sync:"
  echo "  [m]usic"
  echo "  [p]hotos"
  echo "  [s]hared directory"
  echo "  [a]ll (default)"
  read -p "> " input
  case "$input" in
    [m] ) sync_music;;
    [p] ) sync_photos;;
    [s] ) sync_shared_directory;;
    * ) sync_music; sync_photos; sync_shared_directory;;
  esac
}

sync_music() {
  echo -e "$blue====> Syncing music$endcol"
  adb-sync --delete "$music" "$phone_music"
}

sync_photos() {
  echo -e "$blue====> Syncing photos$endcol"
  adb-sync --reverse --delete "$phone_photos" "$photos"
}

sync_shared_directory() {
  echo -e "$blue====> Syncing shared_directory$endcol"
  adb-sync --delete "$shared_directory" "$phone_shared_directory"
}

menu
